swagger: '2.0'
info:
  description: '# Introduction'
  title: backend
  version: v1
schemes:
  - http
basePath: /api
consumes:
  - application/json
produces:
  - application/json
definitions:
  Pong:
    type: object
    properties:
      text:
        type: string
  Recommendation:
    type: object
    required:
      - articul
      - shopName
      - price
      - barcode 
      - url
    properties:
      articul:
        type: string
      shopName:
        type: string
      price:
        type: number
        format: int64
      barcode:
        type: string
      url:
        type: string
  FilterValues:
    type: array
    description: Список значений для фильтра
    items:
      $ref: '#/definitions/KeyValue'
  KeyValue:
    type: object
    properties:
      key:
        type: string
        description: Ключ
        readOnly: true
        x-omitempty: false
      value:
        type: string
        description: Значение
        readOnly: true
        x-omitempty: false
  ID:
    type: object
    properties:
      id:
        type: integer
  GenericError:
    properties:
      code:
        format: int
        type: integer
        x-go-name: Code
        readOnly: true
        x-omitempty: false
      message:
        type: string
        x-go-name: Msg
        readOnly: true
        x-omitempty: false
    additionalProperties:
      type: object
    type: object

parameters:
  barcode:
    in: path
    name: barcode
    required: true
    type: string
  filters:
    in: query
    name: filters
    type: string
    default: ""
responses:
  GenericError:
    description: Generic error
    schema:
      $ref: '#/definitions/GenericError'
paths:
  /recommendations/{barcode}:
    get:
      summary: Получить рекомендации по штрихкоду 
      parameters:
        - in: path
          name: barcode
          type: string
          required: true
          description: штрихкод товара
      responses:
        '200':
          description: 'список альтернатив'
          schema:
            type: array
            items:
              $ref: '#/definitions/Recommendation'
        '400':
          description: 'ошибка'
          schema:
            $ref: '#/definitions/GenericError'
  /recommendations/:
    post:
      summary: Получить рекомендации по штрихкоду с изображения
      parameters:
        - in: formData
          name: content
          type: file
          required: true
          description: Изображение со штрикодом
      consumes:
        - multipart/form-data
      responses:
        '200':
          description: 'перечисление альтернатив'
          schema:
            type: array
            items:
              $ref: '#/definitions/Recommendation'
        '400':
          description: 'ошибка'
          schema:
            $ref: '#/definitions/GenericError'
  /recommendations/analyze/:
    post:
      summary: Получить рекомендации по штрихкоду с изображения
      parameters:
        - in: formData
          name: content
          type: file
          required: true
          description: Изображение со штрикодом
      consumes:
        - multipart/form-data
      responses:
        '200':
          description: 'перечисление альтернатив'
          schema:
            type: array
            items:
              $ref: '#/definitions/Recommendation'
        '400':
          description: 'ошибка'
          schema:
            $ref: '#/definitions/GenericError'
  /ping:
    get:
      summary: Проверка работоспособности сервиса
      consumes:
        - application/json
      responses:
        '200':
          description: 'успешный ответ'
          schema:
            $ref: '#/definitions/Pong'